site_name: Ilyass Khaleq Mansourui
theme:
  name: "ivory"

nav:
  - Introducción: introduccio.md
  - Ubuntu:
      - Sprint 2: sprint2.md
      - Sprint 3: sprint3.md
      - Sprint 4: sprint4.md
      - Sprint 5: sprint5.md
  - Windows:
      - Sprint 1: sprint_1.md
      - Sprint 2: sprint_2.md
      - Sprint 3: sprint_3.md
      - Sprint 4: sprint_4.md
      - Sprint 5: sprint_5.md
